-- =========================================================
-- Oracle Database Objects & Administration
-- Covers Views, Sequences, DDL, Joins, Tablespaces & Users
-- =========================================================


-- =========================================================
-- SECTION 1 : VIEWS
-- =========================================================

DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50) NOT NULL,
    EMP_SALARY NUMBER(10,2),
    DEPT_ID NUMBER
);

INSERT INTO EMPLOYEE VALUES (101,'Ashish Khadka',50000,10);
INSERT INTO EMPLOYEE VALUES (102,'Sita Sharma',45000,20);
INSERT INTO EMPLOYEE VALUES (103,'Ram Thapa',60000,10);
INSERT INTO EMPLOYEE VALUES (104,'Hari KC',55000,30);
INSERT INTO EMPLOYEE VALUES (105,'Gita Rai',48000,20);
INSERT INTO EMPLOYEE VALUES (106,'Bikash Gurung',70000,30);
INSERT INTO EMPLOYEE VALUES (107,'Nisha Adhikari',52000,10);
INSERT INTO EMPLOYEE VALUES (108,'Prakash Bhandari',65000,40);
INSERT INTO EMPLOYEE VALUES (109,'Anita Joshi',47000,20);
INSERT INTO EMPLOYEE VALUES (110,'Rohan Shrestha',58000,40);
INSERT INTO EMPLOYEE VALUES (112,'Manisha Shrestha',58000,70);

CREATE TABLE DEPARTMENT(
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50)
);

INSERT INTO DEPARTMENT VALUES (10,'Human Resources');
INSERT INTO DEPARTMENT VALUES (20,'Finance');
INSERT INTO DEPARTMENT VALUES (30,'Information Technology');
INSERT INTO DEPARTMENT VALUES (40,'Marketing');
INSERT INTO DEPARTMENT VALUES (50,'Administration');
INSERT INTO DEPARTMENT VALUES (60,'Technology');
INSERT INTO DEPARTMENT VALUES (70,'Sales');

COMMIT;

-- Create a View
-- USED TO VIEW VIRTUAL TABLE 
CREATE VIEW EMP_VIEWS AS
SELECT EMP_ID, EMP_NAME
FROM EMPLOYEE;

-- Display data from View
SELECT *
FROM EMP_VIEWS;

-- Drop View
DROP VIEW EMP_VIEW;


-- =========================================================
-- SECTION 2 : SEQUENCE
-- =========================================================

-- Create Sequence
CREATE SEQUENCE EMP_SEQ
START WITH 111
INCREMENT BY 1;

-- Generate Next Value
SELECT EMP_SEQ.NEXTVAL
FROM DUAL;

-- Display Current Value
SELECT EMP_SEQ.CURRVAL
FROM DUAL;


-- =========================================================
-- SECTION 3 : TABLE MODIFICATION
-- =========================================================

-- Add Column
ALTER TABLE EMPLOYEE
ADD EMAIL VARCHAR2(50);

-- Modify Column
ALTER TABLE EMPLOYEE
MODIFY EMAIL VARCHAR2(100);

-- Drop Column
ALTER TABLE EMPLOYEE
DROP COLUMN EMAIL;

-- Rename Table
RENAME EMPLOYEE TO EMP;

-- Rename Back
RENAME EMP TO EMPLOYEE;

-- Rename Column
ALTER TABLE EMPLOYEE
RENAME COLUMN EMP_NAME TO EMPLOYEE_NAME;


-- =========================================================
-- SECTION 4 : TABLE MANAGEMENT
-- =========================================================

-- Remove all rows
TRUNCATE TABLE EMPLOYEE;

-- Drop Table
DROP TABLE EMPLOYEE;


-- =========================================================
-- SECTION 5 : SET OPERATORS
-- =========================================================

-- UNION
SELECT DEPT_ID
FROM EMPLOYEE
UNION
SELECT DEPT_ID
FROM DEPARTMENT;

-- UNION ALL
SELECT DEPT_ID
FROM EMPLOYEE
UNION ALL
SELECT DEPT_ID
FROM DEPARTMENT;


-- =========================================================
-- SECTION 6 : JOINS
-- =========================================================

-- INNER JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- LEFT JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- RIGHT JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- FULL JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E
FULL JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- CROSS JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D;

-- NATURAL JOIN
SELECT *
FROM EMPLOYEE
NATURAL JOIN DEPARTMENT;

-- SELF JOIN
SELECT E1.EMP_NAME, E2.EMP_NAME
FROM EMPLOYEE E1
JOIN EMPLOYEE E2
ON E1.EMP_ID = E2.EMP_ID;


-- =========================================================
-- SECTION 7 : REFERENTIAL INTEGRITY
-- =========================================================

-- Parent Table
CREATE TABLE DEPARTMENT(
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50)
);

-- Child Table
CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    DEPT_ID NUMBER,
    CONSTRAINT FK_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT(DEPT_ID)
);


-- =========================================================
-- SECTION 8 : PSEUDOCOLUMNS
-- =========================================================

-- Display first five rows
SELECT *
FROM EMPLOYEE
WHERE ROWNUM <= 5;


-- =========================================================
-- SECTION 9 : DUAL
-- =========================================================

-- Display current date
SELECT SYSDATE
FROM DUAL;


-- =========================================================
-- SECTION 10 : TABLESPACES
-- =========================================================

-- Display User Tablespaces
SELECT TABLESPACE_NAME
FROM USER_TABLESPACES;

-- Display Datafiles
SELECT TABLESPACE_NAME, FILE_NAME
FROM DBA_DATA_FILES;

-- Create Tablespace
CREATE TABLESPACE TEST
DATAFILE '/opt/oracle/oradata/XE/TEST.dbf'
SIZE 50M;

-- Add Datafile
ALTER TABLESPACE TEST
ADD DATAFILE '/opt/oracle/oradata/XE/TEST1.dbf'
SIZE 40M;

-- Drop Tablespace
DROP TABLESPACE TEST
INCLUDING CONTENTS AND DATAFILES;


-- =========================================================
-- SECTION 11 : USERS & ROLES
-- =========================================================

-- Display Current Container
SHOW CON_NAME;

-- Display PDBs
SHOW PDBS;

-- Switch Container
ALTER SESSION SET CONTAINER = XEPDB1;

-- Create User
CREATE USER ASHISH
IDENTIFIED BY ASHISH;

-- Create Role
CREATE ROLE DEMO;

-- Grant Privileges
GRANT CREATE SESSION,
      CREATE TABLE
TO DEMO;

-- Assign Role to User
GRANT DEMO TO ASHISH;

-- Verify User
SELECT USERNAME
FROM DBA_USERS
WHERE USERNAME = 'ASHISH';

-- Verify Role Privileges
SELECT *
FROM ROLE_SYS_PRIVS
WHERE ROLE = 'DEMO';

------------------------------------------------------------
--CONSTRAINTS

    --NOT NULL CONSTRAINT
--COLUMN CANNOT CONTAIN NULL (EMPTY) VALUES
CREATE TABLE EMPLOYEE1(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50) NOT NULL,
    EMP_SALARY NUMBER(10,2)
);

SELECT * FROM EMPLOYEE1;

INSERT INTO EMPLOYEE1
VALUES(1, 'Ayush Khadka', 50000);

    -- UNIQUE CONSTRAINTS
-- ALL VALUES ARE UNIQUE
CREATE TABLE STUDENT1(
    STUDENT_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) UNIQUE,
    NAME VARCHAR2(50)
);

INSERT INTO STUDENT1
VALUES(101, 'ashish@gmail.com', 'Ashish');

INSERT INTO STUDENT1
VALUES(102, 'sita@gmail.com', 'Sita');


--Primary Key
--A PRIMARY KEY is a constraint that uniquely identifies each record in a table. It does not allow duplicate or NULL values.

-- Foreign Key
--A FOREIGN KEY is a constraint that establishes a relationship between two tables and ensures that values in the child table exist in the parent table.


-------------------------------------------------------------
    
    --SEQUENCE
--AUTOMATICALLY GENERATES UNIQUE SEQUENTIAL NUMBERS/

CREATE TABLE STUDENTS(
    STD_ID NUMBER PRIMARY KEY,
    STD_NAME VARCHAR2(20)
);

CREATE SEQUENCE STD_SEQ 
START WITH 10 INCREMENT BY 1;

INSERT INTO STUDENTS VALUES(STD_SEQ.NEXTVAL, 'ASHISH');
INSERT INTO STUDENTS VALUES(STD_SEQ.NEXTVAL, 'ANIS');


SELECT * FROM STUDENTS;


-----------------------------------------------------

    --PSEUDOCOLUMNS
--SPECIAL COLUMNS THAT ARE NOT PHYSICALLY STORED IN TABLE BUT BEHAVE LIKE TABLE COLUMNS AND RETURN USEFUL INFORMATION

--Common Pseudocolumns
--ROWNUM
--ROWID
--LEVEL
--NEXTVAL
--CURRVAL

    --  ROWNUM
-- ASSIGNS A ROW NUMBER TO EACH ROW RETURNED BY A QUERY, STARTING FROM 1
-- AS DISPLAY FIRST 5 ROWS
SELECT * FROM EMPLOYEE WHERE ROWNUM <= 5;

    -- ROWID
-- RETURN THE UNIQUE PHYSICAL ADDRESS OF EACH ROW IN THE DATABASE
SELECT ROWID, EMP_ID, EMP_NAME FROM EMPLOYEE;


-- SEQUENCE CREATED FOR NEXTVAL AND CURRVAL
CREATE SEQUENCE EMP_SEQUENCE
START WITH 101
INCREMENT BY 1;

--NEXTVAL
SELECT EMP_SEQUENCE.NEXTVAL FROM DUAL;

-- CURRVAL
SELECT EMP_SEQUENCE.NEXTVAL FROM DUAL;

--------------------------------------------------------------
    --SUBQUERIES
-- QUERY WRITTEN INSIDE ANOTHER SQL QUERY
SELECT * FROM EMPLOYEE
WHERE EMP_SALARY = (
    SELECT MAX(EMP_SALARY) FROM EMPLOYEE
);

SELECT EMP_NAME FROM EMPLOYEE 
WHERE EMP_SALARY IN (
    SELECT EMP_SALARY FROM EMPLOYEE WHERE EMP_SALARY > 50000
);


--------------------------------------------------------------------
    -- DATA DICTIONARY
-- COLLECTION OF SYSTEM TABLES AND VIEWS THAT STORES INFORMATION ABOUT THE DATABASE.

    -- USER_TABLES
-- DISPLAY TABLES OWNED NY CURRENT USER
SELECT * FROM TAB;
SELECT * FROM USER_TABLES;

    -- USER_TAB_COLUMNS
-- DISPLAY COLUMN OF TABLES OWNED BY CURRENT USER
SELECT COLUMN_NAME, DATA_TYPE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'EMPLOYEE';

    -- USER_SEQUENCE
-- USER-CREATED SEQUENCE
SELECT * FROM USER_SEQUENCES;

    -- USER_CONSTRAINTS
-- CONSTRAINTS ON USER TABLES
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMPLOYEE';

    -- USER_USERS
-- DISPLAY INFORMATION ABOUT CURRENT USER
SELECT USERNAME
FROM USER_USERS;

-- LOOK FOR DATA
SELECT * FROM EMPLOYEE;
DESC EMPLOYEE;
SELECT * FROM DEPARTMENT;
DESC DEPARTMENT;

-------------------------------------------------------------------
    -- REPORTS
-- PROVIDE REPORT FORMAT. RUNS BY (F5) WHICH IS SCRIPT FORMAT.
-- EVERYTHING I TURN ON SHOULD BE OFF

SPOOL /home/ashishkhadka/Documents/PL|SQL\EMPREPORT.TXT
-- SPOOL FOR SAVING INTO FILES FORMAT IN COMPUTER

SET PAGESIZE 20
SET LINESIZE 100

TTITLE LEFT 'EMPLOYEE REPORT'
BTITLE LEFT 'END REPORT'

COLUMN EMP_NAME FORMAT A15
COLUMN DEPT_NAME FORMAT A25

SELECT E.EMP_ID "EMP ID",
       E.EMP_NAME "EMP NAME",
       E.EMP_SALARY "EMP SALARY",
       D.DEPT_NAME "DEPT NAME"
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

TTITLE OFF
BTITLE OFF
CLEAR COLUMNS
SPOOL OFF

-----------------------------------------------------------
    -- INPUT VARIABLE
SELECT * FROM EMPLOYEE;
ACCEPT ENAME CHAR PROMPT 'PLEASE EMPLOYEE NAME:'
SELECT * FROM EMPLOYEE WHERE EMP_NAME = '&ENAME';

    -- DEFINE VARIABLE
SELECT * FROM EMPLOYEE;
DEFINE EID = 102;
SELECT * FROM EMPLOYEE WHERE EMP_ID = &EID;

















