SELECT * FROM EMPLOYEE;

CREATE TABLE NEW_EMPLOYEE(
    ID NUMBER PRIMARY KEY,
    SALARY NUMBER NOT NULL,
    MESSAGE VARCHAR2(50)
);

COMMIT;

SELECT * FROM NEW_EMPLOYEE;


-- TRIGGERS
CREATE OR REPLACE TRIGGER TRIGGER_EMP
    AFTER UPDATE OF EMP_SALARY 
    ON EMPLOYEE
    FOR EACH ROW 
BEGIN 
    INSERT INTO NEW_EMPLOYEE ( ID, SALARY, MESSAGE)
    VALUES(:OLD.EMP_ID, :NEW.EMP_SALARY,'RECORD IS UPDATED');
END;
/

UPDATE EMPLOYEE SET EMP_SALARY = 10000 WHERE EMP_ID = 101;


-- PROCEDURE IN PL/SQL
CREATE OR REPLACE PROCEDURE WELCOME
AS
BEGIN 
DBMS_OUTPUT.PUT_LINE('WELCOME TO IT EXPERT');
END;
/

BEGIN 
WELCOME;
END;
/

SET SERVEROUTPUT ON;

-- NEXT PROCEDURE EXAMPLE

CREATE OR REPLACE PROCEDURE INSERT_DEPT(
    DEPT_ID IN NUMBER,
    DEPT_NAME IN VARCHAR2)
IS
BEGIN
INSERT INTO DEPARTMENT VALUES (DEPT_ID, DEPT_NAME);
END;
/

SELECT * FROM DEPARTMENT;

BEGIN 
    INSERT_DEPT(70, 'RECEPTION');
END;
/

-- NEXT EXAPMLE
CREATE OR REPLACE PROCEDURE UPDATE_EMP(
    P_ID     IN NUMBER,
    P_AMOUNT IN NUMBER,
    D        OUT NUMBER
)
IS
BEGIN
    UPDATE EMPLOYEE
    SET EMP_SALARY = EMP_SALARY + P_AMOUNT
    WHERE EMP_ID = P_ID;

    SELECT EMP_SALARY
    INTO D
    FROM EMPLOYEE
    WHERE EMP_ID = P_ID;
        
        DBMS_OUTPUT.PUT_LINE(D);
    
END UPDATE_EMP;
/

VARIABLE K NUMBER;

EXEC UPDATE_EMP(112, 10000, :K);

PRINT K;

SELECT * FROM EMPLOYEE;


-- FUNCTION IN PL/SQL

-- SUM OF TWO NUMBER AND DISPLAY OUTPUT
CREATE OR REPLACE FUNCTION ADD_NUMBER(
        N1 IN NUMBER, N2 IN NUMBER )
        
    RETURN NUMBER 
    IS N3 NUMBER;
BEGIN
    N3 := N2 + N1;
    RETURN N3;
END ADD_NUMBER;
/

DECLARE 
    N3 NUMBER;
BEGIN
    N3 := ADD_NUMBER(15, 200);
    DBMS_OUTPUT.PUT_LINE('ADDITION IS : ' || N3);
END;
/

SET SERVEROUTPUT ON;

-- NEXT EXAMPLE

CREATE OR REPLACE FUNCTION UPDATE_SAL(
    ID IN NUMBER, AMOUNT IN NUMBER) 
    
RETURN NUMBER
IS
    D NUMBER;

BEGIN
    UPDATE EMPLOYEE 
    SET EMP_SALARY = EMP_SALARY + AMOUNT
    WHERE EMP_ID = ID;
    
    SELECT EMP_SALARY1 INTO D FROM EMPLOYEE WHERE EMP_ID = ID;
    DBMS_OUTPUT.PUT_LINE('NEW SALARY: '||D);
    RETURN D;
END UPDATE_SAL;
/

DECLARE 
    D NUMBER;
BEGIN
    D:=UPDATE_SAL(103, 10000);
END;
/

SELECT * FROM EMPLOYEE;


    -- EXCEPTION HANDLING
-- PREDEFINED EXCEPTION
-- USER-DEFINED EXCEPTION

-- PRE-DEFINED EXCEPTION
DECLARE
    E_ID EMPLOYEE.EMP_ID % TYPE;
    E_NAME EMPLOYEE.EMP_NAME % TYPE;
BEGIN
    SELECT EMP_NAME INTO E_NAME
    FROM EMPLOYEE
    WHERE EMP_ID = &E_ID;
    
    DBMS_OUTPUT.PUT_LINE(E_NAME);

    EXCEPTION
    WHEN NO_DATA_FOUND 
    THEN
        DBMS_OUTPUT.PUT_LINE('NO RECORD FOUND');
    
    WHEN OTHERS 
    THEN
        DBMS_OUTPUT.PUT_LINE('ERROR!');

END;
/

SET SERVEROUTPUT ON;


-- RISING EXCEPTION
DECLARE
    N NUMBER := &N;
    EX_INVALID EXCEPTION;
BEGIN
    IF N>=10 THEN
    RAISE EX_INVALID ;
    ELSE 
    DBMS_OUTPUT.PUT_LINE('N IS LESS THAN 10');
    END IF;

    EXCEPTION WHEN EX_INVALID THEN
    DBMS_OUTPUT.PUT_LINE('N IS GREATER THAN 10');
    
END;
/

-- USER-DEFINIED EXCEPTION

DECLARE
    E_ID EMPLOYEE.EMP_ID % TYPE := &E_ID;
    E_NAME EMPLOYEE.EMP_NAME % TYPE;
    
    EX_INVALID EXCEPTION;
BEGIN
    IF E_ID < 100 THEN
        RAISE EX_INVALID;
    ELSE
        SELECT EMP_NAME INTO E_NAME 
        FROM EMPLOYEE 
        WHERE EMP_ID = E_ID;
        
        DBMS_OUTPUT.PUT_LINE(E_NAME);
END IF;
    EXCEPTION 
    
    WHEN EX_INVALID THEN
        DBMS_OUTPUT.PUT_LINE('ID MUST BE GREATER THAN HUNDRED');
        
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SUCH EMPLOYEE');
        
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR');
  
END;
/

-- PACKAGE IN PL/SQL





