SELECT * FROM EMPLOYEE;

CREATE TABLE NEW_EMPLOYEE(
    ID NUMBER PRIMARY KEY,
    SALARY NUMBER NOT NULL,
    MESSAGE VARCHAR2(50)
);

COMMIT;

SELECT * FROM NEW_EMPLOYEE;


-- TRIGGERS
CREATE OR REPLACE TRIGGER TRIGGER_EMP
    AFTER UPDATE OF EMP_SALARY 
    ON EMPLOYEE
    FOR EACH ROW 
BEGIN 
    INSERT INTO NEW_EMPLOYEE ( ID, SALARY, MESSAGE)
    VALUES(:OLD.EMP_ID, :NEW.EMP_SALARY,'RECORD IS UPDATED');
END;
/

UPDATE EMPLOYEE SET EMP_SALARY = 10000 WHERE EMP_ID = 101;


-- PROCEDURE IN PL/SQL
CREATE OR REPLACE PROCEDURE WELCOME
AS
BEGIN 
DBMS_OUTPUT.PUT_LINE('WELCOME TO IT EXPERT');
END;
/

BEGIN 
WELCOME;
END;
/

SET SERVEROUTPUT ON;

-- NEXT PROCEDURE EXAMPLE

CREATE OR REPLACE PROCEDURE INSERT_DEPT(
    DEPT_ID IN NUMBER,
    DEPT_NAME IN VARCHAR2)
IS
BEGIN
INSERT INTO DEPARTMENT VALUES (DEPT_ID, DEPT_NAME);
END;
/

SELECT * FROM DEPARTMENT;

BEGIN 
    INSERT_DEPT(70, 'RECEPTION');
END;
/

-- NEXT EXAPMLE
CREATE OR REPLACE PROCEDURE UPDATE_EMP(
    P_ID     IN NUMBER,
    P_AMOUNT IN NUMBER,
    D        OUT NUMBER
)
IS
BEGIN
    UPDATE EMPLOYEE
    SET EMP_SALARY = EMP_SALARY + P_AMOUNT
    WHERE EMP_ID = P_ID;

    SELECT EMP_SALARY
    INTO D
    FROM EMPLOYEE
    WHERE EMP_ID = P_ID;
        
        DBMS_OUTPUT.PUT_LINE(D);
    
END UPDATE_EMP;
/

VARIABLE K NUMBER;

EXEC UPDATE_EMP(112, 10000, :K);

PRINT K;

SELECT * FROM EMPLOYEE;