-- TRIGGERS
SELECT * FROM EMPLOYEE;

CREATE TABLE NEW_EMPLOYEE(
    ID NUMBER PRIMARY KEY,
    SALARY NUMBER NOT NULL,
    MESSAGE VARCHAR2(50)
);

INSERT INTO NEW_EMPLOYEE VALUES (101, 50000, 'Excellent');
INSERT INTO NEW_EMPLOYEE VALUES (102, 45000, 'Good');
INSERT INTO NEW_EMPLOYEE VALUES (103, 60000, 'Promotion Due');

COMMIT;

SELECT * FROM NEW_EMPLOYEE;

