CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50) NOT NULL,
    EMP_SALARY NUMBER(10,2),
    DEPT_ID NUMBER
);

DESC EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(101,'Ashish Khadka',50000,10);
INSERT INTO EMPLOYEE VALUES(102,'Sita Sharma',45000,20);
INSERT INTO EMPLOYEE VALUES(103,'Ram Thapa',60000,10);
INSERT INTO EMPLOYEE VALUES(104,'Hari KC',55000,30);
INSERT INTO EMPLOYEE VALUES(105,'Gita Rai',48000,20);
INSERT INTO EMPLOYEE VALUES(106,'Bikash Gurung',70000,30);
INSERT INTO EMPLOYEE VALUES(107,'Nisha Adhikari',52000,10);
INSERT INTO EMPLOYEE VALUES(108,'Prakash Bhandari',65000,40);
INSERT INTO EMPLOYEE VALUES(109,'Anita Joshi',47000,20);
INSERT INTO EMPLOYEE VALUES(110,'Rohan Shrestha',58000,40);
INSERT INTO EMPLOYEE VALUES(112,'MANISHA Shrestha',58000,70);


COMMIT;

SELECT * FROM EMPLOYEE;

SELECT EMP_ID,EMP_NAME FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE EMP_ID=101;
SELECT * FROM EMPLOYEE WHERE EMP_SALARY>50000;
SELECT * FROM EMPLOYEE WHERE DEPT_ID=20;
SELECT * FROM EMPLOYEE ORDER BY EMP_SALARY ASC;
SELECT * FROM EMPLOYEE ORDER BY EMP_SALARY DESC;
SELECT * FROM EMPLOYEE ORDER BY EMP_NAME;


    -- DISTINCT
-- REMOVE DUPLICATE VALUES
SELECT DISTINCT DEPT_ID FROM EMPLOYEE;


    -- LIKE
-- SEARCH FOR SPECIFIC PATTERN
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE 'A%';
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%a';
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%Sh%';
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '_i%';


-- BETWEEN
SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 50000 AND 65000;


-- IN
SELECT * FROM EMPLOYEE WHERE DEPT_ID IN (10,20);
SELECT * FROM EMPLOYEE WHERE EMP_ID IN (101,103,105);


-- NOT IN
SELECT * FROM EMPLOYEE WHERE DEPT_ID NOT IN (30,40);


    -- AND
-- RETURN ROWS ONLY IF ALL CONDITION ARE TRUE
SELECT * FROM EMPLOYEE WHERE EMP_SALARY>50000 AND DEPT_ID=10;


    -- OR
-- RETURN ROWS IF ONE CONDITION IS TRUE 
SELECT * FROM EMPLOYEE WHERE DEPT_ID=20 OR DEPT_ID=40;


    -- NOT
-- REVERSE THE CONDITION
SELECT * FROM EMPLOYEE WHERE NOT EMP_SALARY>60000;


-- UPDATE
UPDATE EMPLOYEE SET EMP_SALARY=55000 WHERE EMP_ID=101;

UPDATE EMPLOYEE SET EMP_NAME='Ashish K.', EMP_SALARY=60000 WHERE EMP_ID=101;


-- DELETE
DELETE FROM EMPLOYEE WHERE EMP_ID=110;

ROLLBACK;


-- AGGREGATE FUNCTIONS
    --COUNT()	COUNT THE NUMBER OF ROWS
    --SUM()	    CALCULATE THE TOTAL OF NUMERIC VALUES
    --AVG()	    CALCULATE THE AVERAGE OF NUMERIC VALUES
    --MAX()	    FINDS THE HIGHEST VALUE
    --MIN()	    FINDS THE LOWEST VALUE

SELECT COUNT(*) FROM EMPLOYEE;

SELECT SUM(EMP_SALARY) FROM EMPLOYEE;

SELECT AVG(EMP_SALARY) FROM EMPLOYEE;

SELECT MAX(EMP_SALARY) FROM EMPLOYEE;

SELECT MIN(EMP_SALARY) FROM EMPLOYEE;


    -- GROUP BY
-- GROUP ROWS THAT HAVE SAME VALUES
SELECT DEPT_ID,
COUNT(*) TOTAL_EMPLOYEE
FROM EMPLOYEE
GROUP BY DEPT_ID;

SELECT DEPT_ID,
AVG(EMP_SALARY) AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPT_ID;


    -- HAVING
-- FILTER GROUPS CREATED BY GROUP BY.
SELECT DEPT_ID,
COUNT(*) TOTAL
FROM EMPLOYEE
GROUP BY DEPT_ID
HAVING COUNT(*)>2;


    -- ALIAS
-- TEMPORARY NAME GIVEN TO COLUMN OR TABLE TO MAKE OUTPUT EASIER TO READ
SELECT EMP_NAME AS NAME,
EMP_SALARY SALARY
FROM EMPLOYEE;

    -- ARITHMETIC
-- PERFORMS MATHEMATIC CALCULATIONS
SELECT
EMP_NAME,
EMP_SALARY,
EMP_SALARY*12 AS ANNUAL_SALARY
FROM EMPLOYEE;

SELECT
EMP_NAME,
EMP_SALARY,
EMP_SALARY*0.10 BONUS
FROM EMPLOYEE;

    -- ROWNUM
-- ORACLE PSEUDO-COLUMN THAT ASSIGNS A ROW NUMBER TO EACH RETURNED BY A QUERY, STARTING FORM 1.
SELECT *
FROM EMPLOYEE
WHERE ROWNUM<=5;


-- NULL
SELECT *
FROM EMPLOYEE
WHERE EMP_NAME IS NULL;

SELECT *
FROM EMPLOYEE
WHERE EMP_NAME IS NOT NULL;

-- ALTER TABLE
ALTER TABLE EMPLOYEE
ADD EMAIL VARCHAR2(50);

ALTER TABLE EMPLOYEE
MODIFY EMAIL VARCHAR2(100);

ALTER TABLE EMPLOYEE
DROP COLUMN EMAIL;


-- RENAME TABLE
RENAME EMPLOYEE TO EMP;

RENAME EMP TO EMPLOYEE;


    -- VIEW
-- VIRTUAL TABLE CREATED FROM A RESULT OF AN SQL QUERY.
CREATE VIEW EMP_VIEW AS
SELECT EMP_ID,
EMP_NAME,
EMP_SALARY
FROM EMPLOYEE;

SELECT *
FROM EMP_VIEW;

DROP VIEW EMP_VIEW;


    -- SEQUENCE
-- DATABASE OBJECT THAT GENERATES UNIQUE SEQUENTIAL NUMBERS, COMMONLY USED FOR PRIMARY KEYS.
    -- "KEYWORDS"
    --  NEXTVAL	    Generates the next sequence value
    --  CURRVAL	    Returns the current sequence value (after NEXTVAL has been used in the session)

CREATE SEQUENCE EMP_SEQ
START WITH 111
INCREMENT BY 1;

INSERT INTO EMPLOYEE
VALUES(EMP_SEQ.NEXTVAL,'New Employee',45000,50);



    -- TRANSACTION
-- LOGICAL UNIT OF WORK CONSISTING OF ONE OR MORE SQL STATEMENTS THAT ARE EXECUTED TOGETHER.
    
    -- "COMMAND"
    --  COMMIT       SAVE CHANGES PERMANENTLY
    --  ROLLBACK     UNDO CHANGES SINCE LAST COMMIT 
    --  SAVPOINT     CREATE A POINT TO ROLL BACK

SAVEPOINT SP1;

UPDATE EMPLOYEE
SET EMP_SALARY=70000
WHERE EMP_ID=102;

SELECT * FROM EMPLOYEE;

ROLLBACK TO SP1;

COMMIT;


-- DATE
SELECT SYSDATE
FROM DUAL;


    -- TRUNCATE
-- REMOVE ALL ROWS FROM THE TABLE QUICKELY, BUT KEEPS THE TABLE STRUCTURE.
TRUNCATE TABLE EMPLOYEE;


    -- DROP TABLE
-- PERMANENTLY REMOVES A DATABASE OBJECT.
DROP TABLE EMPLOYEE;

-- CREATE TABLE DEPARTMENT
CREATE TABLE DEPARTMENT (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50)
);

DROP TABLE DEPARTMENT;

INSERT INTO Department VALUES (10, 'Human Resources');
INSERT INTO Department VALUES (20, 'Finance');
INSERT INTO Department VALUES (30, 'Information Technology');
INSERT INTO Department VALUES (40, 'Marketing');
INSERT INTO Department VALUES (50, 'Administration');
INSERT INTO DEPARTMENT VALUES (60, 'TECHNOLOGY');

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

DESC EMPLOYEE;
DESC DEPARTMENT;


    --  UNION 
-- COMBINES THE RESULT OF TWO OR MORE SELECT STATEMENTS INTO SINGLE RESULT SET AND AUTOMATICALLY REMOVES DUPLICATE ROWS.
SELECT DEPT_ID FROM EMPLOYEE UNION SELECT DEPT_ID FROM DEPARTMENT;

    --UNION ALL
-- KEEPS DUBLICATE ROWS
SELECT DEPT_ID FROM EMPLOYEE UNION ALL SELECT DEPT_ID FROM DEPARTMENT ORDER BY DEPT_ID;


                            -- "JOIN"
    -- INNER JOIN
-- RETURN ONLY THE ROWS THAT HAVE MATCHING VALUES IN BOTH TABLES.
SELECT E.EMP_ID, E.EMP_NAME, E.EMP_SALARY, D.DEPT_NAME
FROM EMPLOYEE E INNER JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

    -- LEFT JOIN
-- ALL ROWS FROM LEFT TABLE + MATCHIING ROWS FROM THE RIGHT TABLE
SELECT E.EMP_ID, E.EMP_NAME, E.EMP_SALARY, D.DEPT_NAME
FROM EMPLOYEE E LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

    -- RIGHT JOIN
-- ALL ROWS FORM THE RIGHT TABLE + MATCHING ROWS FROM THE LEFT TABLE
SELECT E.EMP_ID, E.EMP_NAME, E.EMP_SALARY, D.DEPT_NAME
FROM EMPLOYEE E RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

    -- FULL JOIN
-- RETURN ALL ROWS FROM THE JOINED TABLE WHETHER THEY ARE MATCHED OR NOT.
SELECT E.EMP_ID, E.EMP_NAME, E.EMP_SALARY, D.DEPT_NAME
FROM EMPLOYEE E FULL JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

    -- CROSS JOIN
-- ALL ROWS FORM FIRST TABLE JOIN WITH ALL THE ROWS OF SECOND TABLE.
SELECT E.EMP_ID, E.EMP_NAME, E.EMP_SALARY, D.DEPT_ID
FROM EMPLOYEE E CROSS JOIN DEPARTMENT D;

    -- NATURAL JOIN
-- COMPARE ALL COLUMNS IN BOTH TABLE AND RETURN ALL MATCH RECORD.
SELECT E.EMP_ID, E.EMP_NAME, E.EMP_SALARY, D.DEPT_NAME
FROM EMPLOYEE E NATURAL JOIN DEPARTMENT D;

    -- SLEF JOIN
-- TABLE IS JOINED WITH ITSELF
SELECT E1.EMP_ID, E2.EMP_NAME, E1.EMP_SALARY
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.EMP_ID = E2.EMP_ID;

