--1. Create Student Table
CREATE TABLE STUDENT (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    AGE NUMBER,
    MARKS NUMBER
);
Insert Records
INSERT INTO STUDENT VALUES (1, 'RAM', 20, 49);
INSERT INTO STUDENT VALUES (2, 'SITA', 19, 90);
INSERT INTO STUDENT VALUES (3, 'HARI', 21, 70);

COMMIT;
Display Records
SELECT * FROM STUDENT;

SELECT NAME, MARKS
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE MARKS > 75;
--2. UPDATE and DELETE
Update Marks
UPDATE STUDENT
SET MARKS = 85
WHERE ID = 1;

COMMIT;
Delete Record
DELETE FROM STUDENT
WHERE ID = 3;

COMMIT;
--3. Sorting and Filtering
SELECT *
FROM STUDENT
ORDER BY MARKS DESC;

SELECT *
FROM STUDENT
WHERE MARKS BETWEEN 70 AND 90;

SELECT *
FROM STUDENT
WHERE NAME LIKE 'S%';
--4. Aggregate Functions
SELECT
    AVG(MARKS) AS AVERAGE,
    MAX(MARKS) AS MAXIMUM,
    MIN(MARKS) AS MINIMUM
FROM STUDENT;
Count Students
SELECT COUNT(*)
FROM STUDENT;
Group By
SELECT AGE,
       COUNT(*) AS TOTAL_STUDENTS
FROM STUDENT
GROUP BY AGE;
Subquery
SELECT *
FROM STUDENT
WHERE MARKS >
(
    SELECT AVG(MARKS)
    FROM STUDENT
);
Display Name and Marks
SELECT NAME, MARKS
FROM STUDENT
ORDER BY MARKS DESC;
--5. Sequence
Create Sequence
CREATE SEQUENCE PROD_SEQ
START WITH 1
INCREMENT BY 1;
Create Product Table
CREATE TABLE PRODUCT
(
    P_ID NUMBER PRIMARY KEY,
    P_NAME VARCHAR2(50),
    PRICE NUMBER
);
Insert Records
INSERT INTO PRODUCT VALUES (PROD_SEQ.NEXTVAL,'Pen',10);
INSERT INTO PRODUCT VALUES (PROD_SEQ.NEXTVAL,'Book',50);
INSERT INTO PRODUCT VALUES (PROD_SEQ.NEXTVAL,'Bag',500);

COMMIT;
Display Products
SELECT *
FROM PRODUCT;
--6. Recycle Bin
Create Table
CREATE TABLE TESTTABLE
(
    ID NUMBER,
    NAME VARCHAR2(50)
);
Insert Data
INSERT INTO TESTTABLE
VALUES (1,'Ram');

COMMIT;
Drop Table
DROP TABLE TESTTABLE;
View Recycle Bin
SHOW RECYCLEBIN;
Restore Table
FLASHBACK TABLE TESTTABLE TO BEFORE DROP;
Permanently Delete
PURGE TABLE TESTTABLE;
--7. Department and Employee (JOIN)
Create Department
CREATE TABLE DEPARTMENT
(
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50)
);
Create Employee
CREATE TABLE EMPLOYEE
(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    SALARY NUMBER,
    DEPT_ID NUMBER,
    CONSTRAINT FK_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT(DEPT_ID)
);
Insert Departments
INSERT INTO DEPARTMENT VALUES (1,'HR');
INSERT INTO DEPARTMENT VALUES (2,'IT');
INSERT INTO DEPARTMENT VALUES (3,'Finance');
Insert Employees
INSERT INTO EMPLOYEE VALUES (101,'Ram',35000,1);
INSERT INTO EMPLOYEE VALUES (102,'Sita',60000,2);
INSERT INTO EMPLOYEE VALUES (103,'Hari',45000,2);
INSERT INTO EMPLOYEE VALUES (104,'Gita',55000,3);
INSERT INTO EMPLOYEE VALUES (105,'Milan',30000,1);

COMMIT;
--8. Project Table
CREATE TABLE PROJECT
(
    PROJECT_ID NUMBER PRIMARY KEY,
    PROJECT_NAME VARCHAR2(50),
    EMP_ID NUMBER,
    CONSTRAINT FK_EMP
    FOREIGN KEY (EMP_ID)
    REFERENCES EMPLOYEE(EMP_ID)
);
Insert Projects
INSERT INTO PROJECT VALUES (1,'Payroll',101);
INSERT INTO PROJECT VALUES (2,'Website',102);
INSERT INTO PROJECT VALUES (3,'Mobile App',103);
INSERT INTO PROJECT VALUES (4,'Accounting',104);

COMMIT;
--9. JOIN
SELECT
    E.EMP_NAME,
    D.DEPT_NAME,
    P.PROJECT_NAME,
    E.SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
LEFT JOIN PROJECT P
ON E.EMP_ID = P.EMP_ID;
--10. Subquery
Employees Earning More Than Department Average
SELECT EMP_NAME,
       SALARY
FROM EMPLOYEE E
WHERE SALARY >
(
    SELECT AVG(SALARY)
    FROM EMPLOYEE
    WHERE DEPT_ID = E.DEPT_ID
);
--11. Department with Highest Average Salary
SELECT DEPT_NAME
FROM DEPARTMENT
WHERE DEPT_ID =
(
    SELECT DEPT_ID
    FROM EMPLOYEE
    GROUP BY DEPT_ID
    ORDER BY AVG(SALARY) DESC
    FETCH FIRST 1 ROW ONLY
);
--12. Employees Without Project
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_ID NOT IN
(
    SELECT EMP_ID
    FROM PROJECT
);
--------------------------------------------------------------------
-- NOTION PRACTICES

--2
CONNECT scott/tiger;

SET LINESIZE 120
SET PAGESIZE 30

DESC emp;

SELECT*FROM emp;

/

EXIT;
