-- SQL basics

-- CREATE A TABLE 
CREATE TABLE EMP(
  EMP_ID NUMBER PRIMARY KEY,
  EMP_NAME VARCHAR2(50),
  EMP_SALARY DECIMAL(10,2)
);

-- DESCRIPTION OF TABLE
DESC EMP;

-- INSERT DATA INTO TABLE
INSERT INTO EMP VALUES(1, 'ASHISH', 40000);
INSERT INTO EMP VALUES(2, 'AYUSH', 50000);
INSERT INTO EMP VALUES(3, 'ANIL', 60000);

-- SELECT STATEMENT
SELECT * FROM EMP;
SELECT * FROM EMP WHERE EMP_ID = 2;

